# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    turtlebot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    turtlebot_hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


turtlebot_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint1
      - joint2
      - joint3
      - joint4

turtlebot_hand_controller:
  ros__parameters:
    joint: gripper

